# Generated by Django 3.0.6 on 2020-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupas',
            name='photo',
            field=models.ImageField(upload_to='Roupas'),
        ),
    ]
